# Generated by Django 4.2 on 2024-11-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='hashed',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
