# Generated by Django 5.1.1 on 2024-10-18 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_implementation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='Tinan')),
            ],
        ),
        migrations.AddField(
            model_name='projectimplementation',
            name='years',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_year', to='project_implementation.year', verbose_name='Tinan'),
            preserve_default=False,
        ),
    ]
