# Generated by Django 5.1.1 on 2024-10-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_implementation', '0002_year_projectimplementation_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimplementation',
            name='contact_person',
            field=models.CharField(blank=True, max_length=300, verbose_name='Contact Person'),
        ),
    ]
