# Generated by Django 5.1.1 on 2024-10-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_implementation', '0003_alter_projectimplementation_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimplementation',
            name='hashed',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
