# Generated by Django 5.1.1 on 2024-10-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_implementation', '0004_projectimplementation_hashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimplementation',
            name='date',
            field=models.DateField(verbose_name='Data Implemetasaun'),
        ),
    ]
