# Generated by Django 4.2 on 2024-10-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_implementation', '0005_alter_projectimplementation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimplementation',
            name='hashed',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
