# Generated by Django 4.2 on 2024-11-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_implementation', '0006_alter_projectimplementation_hashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=50, null=True, verbose_name='Anual Report')),
                ('upload_file', models.FileField(blank=True, help_text='Upload file PDF', null=True, upload_to='FilePdf/', verbose_name='Dokumen PDF')),
                ('years', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_years', to='project_implementation.year', verbose_name='Tinan')),
            ],
        ),
    ]
