# Generated by Django 4.2 on 2024-10-29 23:32

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('project_implementation', '0006_alter_projectimplementation_hashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('activity_content', froala_editor.fields.FroalaField(verbose_name='Activity Content')),
                ('image', models.ImageField(null=True, upload_to='Posts/')),
                ('date', models.DateField(verbose_name='Data Implemetasaun')),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_category', to='news.category', verbose_name='Category')),
                ('years', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='project_implementation.year', verbose_name='Tinan')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['-date'],
            },
        ),
    ]
