# Generated by Django 4.2 on 2024-11-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ['-date'], 'verbose_name': 'actividade', 'verbose_name_plural': 'actividades'},
        ),
    ]
