# Generated by Django 4.2 on 2024-11-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0003_remove_activities_hashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='hashed',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
